version: '3.8'  # Phiên bản của Docker Compose

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"    
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "85:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

  web:
    build: 
      context: .  # Xây dựng từ thư mục hiện tại
      dockerfile: Dockerfile  # Tên tệp Dockerfile
    ports:
      - "8000:8000"  # Ánh xạ cổng 8000 trên máy host đến cổng 8000 trong container
    depends_on:
      - db
    env_file:
      - .env  # Đảm bảo rằng file .env được chỉ định
    volumes:
      - .:/app  # Ánh xạ thư mục backend vào /app trong container
    environment:
      - PYTHONUNBUFFERED=1 

volumes:
  postgres_data:  # Định nghĩa volume ở đây
