version: '3.8'

services:

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    expose:
      - "8000"  # Sử dụng expose để mở cổng trong mạng Docker
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./backend/staticfiles:/staticfiles  # Đảm bảo thư mục staticfiles đã được tạo và ánh xạ
      - ./nginx.conf:/etc/nginx/nginx.conf  # Gắn tệp cấu hình Nginx
    ports:
      - "80:80"
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}  # Email đăng nhập cho pgAdmin
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}  # Mật khẩu cho pgAdmin
    ports:
      - "8085:80"  # Ánh xạ cổng để truy cập pgAdmin
    depends_on:
      - db

volumes:
  postgres_data:
