name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test  # Thay thế bằng lệnh test của bạn

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Đảm bảo rằng việc xây dựng đã hoàn thành

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USER@$HOST << 'EOF'
            git pull origin main  # Hoặc nhánh mà bạn muốn triển khai
            cd English_Application_API/backend/
            docker-compose up --build -d  # Khởi động lại dịch vụ Docker
          EOF
