name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
      - develop
  pull_request:
    branches:
      - vocabulary
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Đăng nhập vào Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH to server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: sshpass -p "$SSH_PASSWORD" ssh root@engina.duytech.site "cd English_Application_API && git pull origin dev && docker-compose up --build"

